export const TOGGLE_FAVE = 'TOGGLE_FAVE'
export const CLICK_DETAILS = 'CLICK_DETAILS'

//these are for the API call
export const DETAILS_HAS_ERRORED = 'DETAILS_HAS_ERRORED'
export const DETAILS_IS_LOADING = 'DETAILS_IS_LOADING'
export const DETAILS_FETCH_DATA_SUCCESS = 'DETAILS_FETCH_DATA_SUCCESS'
